project(task3)

add_executable(SimUDuck3 Main.cpp
        Duck/Duck.h
        Duck/MallardDuck.h
        Duck/Behaviors/QuackBehaviors.h
        Duck/Behaviors/FlyBehaviors.h
        Duck/Behaviors/DanceBehaviors.h
        DuckFunctions.h
        Duck/RedHeadDuck.h
        Duck/ArtificialDuck.h
        Duck/DecoyDuck.h)